name: build-and-lint

on: push

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["^3.10"]
        poetry-version: ["1.1.13"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install deps
        run: poetry install
      - name: List deps and poetry version
        run: poetry show && poetry -V
      - name: lint
        run: make lint
