  name: ci

  on: [push]
  jobs:
    build_and_lint:
      uses: artemBeletzky/python-project-lvl1/.github/workflows/build.yml@main
    lint:
      runs-on: macos-latest
      needs: build_and_lint
      steps:
        - name: lint
          run: make lint